name: Publish CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm run prod --if-present

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.4.1
        with:
          commit_message: publish dist
          branch: ${{ github.head_ref }}
          push_options: '--force'
          skip_dirty_check: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}