name: Stale

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * * # Daily at 00:00 UTC

jobs:
  stale:
    name: Stale
    runs-on: appart-runners
    steps:
      - name: Stale
        uses: appart-media/actions/stale@3
        with:
          token: ${{ secrets.GH_ORG_PAT }}

